export const CROPS = [
  "Tomatoes (Nyanya)",
  "Onions (Kitunguu)",
  "Beans (Maharagwe)",
  "Cabbage (Kabeji)",
  "Carrots (Karoti)",
  "Sukuma Wiki (Kale)",
  "Avocado (Parachichi)",
  "Maize (Mahindi)",
  "Potatoes (Viazi)",
  "Bananas (Ndizi)",
  "Mangoes (Embe)",
  "Watermelon (Tikiti Maji)",
  "Pineapple (Nanasi)",
  "Capsicum (Pilipili Hoho)",
  "Garlic (Kitunguu Saumu)",
  "Ginger (Tangawizi)",
  "Sweet Potatoes (Viazi Vitamu)",
  "Cassava (Muhogo)",
  "Coffee (Kahawa)",
  "Tea (Chai)",
  "Macadamia",
  "Passion Fruit",
  "Oranges (Chungwa)",
  "Lemons (Ndimu)",
  "Spinach",
  "Managu (Black Nightshade)",
  "Terere (Amaranth)",
  "Sagaa (Spider Plant)",
  "Kunde (Cowpea Leaves)",
  "Arrowroots (Nduma)",
  "Wheat (Ngano)",
  "Rice (Mchele)",
  "Sorghum (Mtama)",
  "Millet (Wimbi)",
  "Green Grams (Ndengu)",
  "Cowpeas (Kunde)",
  "Pigeon Peas (Mbaazi)",
  "Groundnuts (Njugu Karanga)",
  "Sunflowers (Alizeti)",
  "Soya Beans",
  "Pumpkin (Malenge)",
  "Cucumber",
  "Eggplant (Biringanya)",
  "Broccoli",
  "Cauliflower",
  "Lettuce",
  "Celery",
  "Parsley",
  "Coriander (Dania)",
  "Mint",
  "Rosemary",
  "Thyme",
  "Basil",
  "Turmeric",
  "Chili (Pilipili)",
  "Black Pepper",
  "Cardamom",
  "Cinnamon",
  "Cloves",
  "Vanilla",
  "Cocoa",
  "Tobacco",
  "Cotton",
  "Pyrethrum",
  "Sisal",
  "Sugar Cane",
  "Cashew Nuts",
  "Coconuts",
  "Betel Nuts",
  "Areca Nuts",
  "Khat (Miraa)",
  "Cannabis (Industrial Hemp)",
  "Aloe Vera",
  "Moringa",
  "Stevia",
  "Jojoba",
  "Castor Beans",
  "Sesame (Simsim)",
  "Linseed (Flax)",
  "Canola",
  "Mustard",
  "Safflower",
  "Niger Seed",
  "Poppy Seed",
  "Chia Seeds",
  "Quinoa",
  "Buckwheat",
  "Amaranth Grain",
  "Teff",
  "Fonio",
  "Spelt",
  "Barley",
  "Oats",
  "Rye",
  "Triticale",
  "Malt",
  "Hops",
  "Grapes",
  "Apples",
  "Pears",
  "Peaches",
  "Plums",
  "Apricots",
  "Cherries",
  "Strawberries",
  "Raspberries",
  "Blueberries",
  "Blackberries",
  "Cranberries",
  "Kiwi Fruit",
  "Pomegranate",
  "Figs",
  "Dates",
  "Olives",
  "Walnuts",
  "Almonds",
  "Hazelnuts",
  "Pistachios",
  "Pecans",
  "Brazil Nuts",
  "Pine Nuts",
  "Chestnuts",
];

export const UNITS = [
  "kg",
  "gunia (90kg)",
  "gunia (50kg)",
  "crate",
  "box",
  "piece",
  "bunch",
  "bucket",
  "debe",
  "tonne",
];
